spawnLocation: spawn
MinPlayer: 4
MaxPlayer: 18
startTimer: 30
pvpLocation:
- 1
- 2
- 3
- 4
- 5
- 6
- 7
- 8
- 9
- 10
- 11
- 12
- 13
- 14
- 15
- 16
- 17
- 18
unbreackable:
- 20
- 95
blockDrop:
  31:
  - 5
  - 0
  - 1
  175:
  - 339
  - 0
  - 3
  17:
  - 5
  - 0
  - 4


spawn:
  x: 0.5
  y: 90.0
  z: 0.5
  yaw: 90.0
  pitch: 0.0
  world: "world"
1:
  x: 30.5
  y: 65
  z: -60.5
  yaw: 90.0
  pitch: 0.0
  world: "world"
2:
  x: -32.5
  y: 71.0
  z: -53.5
  yaw: 270.0
  pitch: 0.0
  world: "world"
3:
  x: 30.5
  y: 65.0
  z: 3.5
  yaw: 90.0
  pitch: 90.0
  world: "world"
4:
  x: -36.5
  y: 63.0
  z: 0.5
  yaw: 270.0
  pitch: 0.0
  world: "world"
5:
  x: 18.5
  y: 64.0
  z: 58.5
  yaw: 90.0
  pitch: 0.0
  world: "world"
6:
  x: -32.5
  y: 68.0
  z: 70.5
  yaw: 270.0
  pitch: 0.0
  world: "world"
7:
  x: -44.5
  y: 68.0
  z: -65.5
  yaw: 90.0
  pitch: 0.0
  world: "world"
8:
  x: -115.5
  y: 64.0
  z: -62.5
  yaw: 270.0
  pitch: 0.0
  world: "world"
9:
  x: -47.5
  y: 63.0
  z: 3.5
  yaw: 90.0
  pitch: 0.0
  world: "world"
10:
  x: -116.5
  y: 67.0
  z: -2.5
  yaw: 270.0
  pitch: 0.0
  world: "world"
11:
  x: -42.5
  y: 66.0
  z: 67.5
  yaw: 90.0
  pitch: 0.0
  world: "world"
12:
  x: -115.5
  y: 67.0
  z: 63.5
  yaw: 270.0
  pitch: 0.0
  world: "world"
13:
  x: -124.5
  y: 64
  z: -64.5
  yaw: 90.0
  pitch: 0.0
  world: "world"
14:
  x: -195.5
  y: 68.0
  z: -62.5
  yaw: 270.0
  pitch: 0.0
  world: "world"
15:
  x: -123.5
  y: 66.0
  z: 0.5
  yaw: 90.0
  pitch: 0.0
  world: "world"
16:
  x: -193.5
  y: 64.0
  z: -23.5
  yaw: 270.0
  pitch: 0.0
  world: "world"
17:
  x: -123.5
  y: 66.0
  z: 57.5
  yaw: 90.0
  pitch: 0.0
  world: "world"
18:
  x: -190.5
  y: 65.0
  z: 78.5
  yaw: 270.0
  pitch: 0.0
  world: "world"